version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  CODECOV_TOKEN: 9b5deb9d-dfbd-487d-a2cd-c5a1e12953ed
before_build:
- pwsh: >-
    dotnet restore

    choco install codecov
build:
  verbosity: minimal
test_script:
- pwsh: >-
    dotnet test --blame ./tests/Xunit.DataAttributes.Tests/Xunit.DataAttributes.Tests.csproj /p:CollectCoverage=true /p:Exclude=\"[xunit.*]*\" /p:CoverletOutputFormat=opencover

    codecov -f "./tests/Xunit.DataAttributes.Tests/coverage.opencover.xml"
artifacts:
- path: '**/*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 1EsewYvmcY1mezJgxG8QGZmrikfpIrr6AiyMuwckiPer+VobTN7xjjMvIN9h0sFd
  artifact: /.*\.nupkg/